spring.datasource.url=jdbc:postgresql://localhost:5432/learnx
spring.datasource.username=postgres
spring.datasource.password=sadhu1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# Spring Security dev defaults
spring.security.user.name=jwt
spring.security.user.password=jwt

# Bean overriding
spring.main.allow-bean-definition-overriding=true